#!/usr/bin/env bash
#
# build-m4.sh - cross-build GNU m4 for x86_64-lariat and package it as an
# installable LPKG1 (m4-<ver>.lpkg).
#
# m4 is the macro processor autoconf is built on: `configure` scripts are
# generated by m4, and autoconf/automake invoke it directly.  It is a
# self-contained C program (gnulib + libc), so it cross-builds with the Phase 1
# cross compiler.  Packaged as a dynamic PIE (depends on libc-dev) installing to
# /usr/bin/m4, mirroring build-make.sh / build-dash.sh.
#
# Usage:  ./build-m4.sh           (fetch + configure + build + package)
# Output: toolchain/packages/m4-<ver>.lpkg
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/versions.sh"

OUT_DIR="${OUT_DIR:-$TC_ROOT/packages}"
MKLPKG="$REPO_ROOT/scripts/mklpkg.sh"
BUILD_HOST="$(cc -dumpmachine 2>/dev/null || gcc -dumpmachine)"
CROSS="$TC_PREFIX/bin/$LARIAT_TARGET-gcc"
SRC="$TC_SRC/m4-$M4_VER"
BLD="$TC_BUILD/m4"

[ -x "$CROSS" ] || { echo "error: cross compiler $CROSS missing; build the toolchain first" >&2; exit 1; }
mkdir -p "$TC_SRC" "$OUT_DIR"
export PATH="$TC_PREFIX/bin:$PATH"

echo "==> fetching m4 $M4_VER"
if [ ! -d "$SRC" ]; then
    file="m4-$M4_VER.tar.xz"
    [ -f "$TC_SRC/$file" ] || (cd "$TC_SRC" && \
        curl -fLO "https://ftp.gnu.org/gnu/m4/$file")
    tar -C "$TC_SRC" -xf "$TC_SRC/$file"
fi

echo "==> configuring m4 ($LARIAT_TARGET, build=$BUILD_HOST)"
rm -rf "$BLD"; mkdir -p "$BLD"
# Cross gnulib needs a couple of run-test results pre-seeded (it cannot execute
# target binaries on the build host); these are the standard musl-safe answers.
( cd "$BLD"
  "$SRC/configure" \
      --host="$LARIAT_TARGET" --build="$BUILD_HOST" \
      --prefix=/usr --disable-nls \
      CC="$CROSS" \
      gl_cv_func_printf_directive_n=yes \
      gl_cv_func_printf_infinite=yes )

echo "==> building"
( cd "$BLD" && make )

M4_BIN="$BLD/src/m4"
[ -f "$M4_BIN" ] || { echo "error: $M4_BIN not produced" >&2; exit 1; }
"$TC_PREFIX/bin/$LARIAT_TARGET-strip" "$M4_BIN" 2>/dev/null || true
file "$M4_BIN"

echo "==> packaging m4-$M4_VER.lpkg"
"$MKLPKG" --name m4 --version "$M4_VER" --deps "libc-dev" \
    --desc "GNU m4 - macro processor (autoconf dependency) - x86_64-lariat" \
    --out "$OUT_DIR/m4-$M4_VER.lpkg" \
    "0755:$M4_BIN:usr/bin/m4"

echo "done: $OUT_DIR/m4-$M4_VER.lpkg"
